### ISSUE TITLE
Tetris-AI mit unserem Env testen

### ISSUE THREAD

**Issue by grittaweisheit** [MichaelBuessemeyer/tetrisRL#1]
https://github.com/nuno-faria/tetris-ai

**Comment by grittaweisheit** [comment]
We observed that adjusting our env wouldn't be very helpful, since it felt like reimplementing the one from tetris ai. Instead we slightly adjusted their env to provide the necessary api to run with our dqn implementation.

the results are on the branch [tetris-ai-env](https://github.com/MichaelBuessemeyer/tetrisRL/tree/tetris-ai-env).

**Comment by MichaelBuessemeyer** [comment]
As we do not follow this path anymore, I close this issue
