### ISSUE TITLE
Run standard score as reward only with I tetromino

### ISSUE THREAD

**Issue by grittaweisheit** [MichaelBuessemeyer/tetrisRL#16]

**Comment by MichaelBuessemeyer** [comment]
![photo_2021-07-15_11-32-01](https://user-images.githubusercontent.com/39529669/125765873-7259e1bc-7b00-46e6-8486-2707e20c772f.jpg)
![photo_2021-07-15_11-34-45](https://user-images.githubusercontent.com/39529669/125765916-e3d2d73d-2a4a-465a-bd21-6efe9b83e738.jpg)
